# Base Jekyll configuration

# Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile.

# Use _config.build.yml to override these settings on `grunt build`.

name: sketchbook
description: nclud's sketchbook
url: http://sketchbook.nclud.com


# Exclude directories and/or files from the conversion.
# Grunt moves image files and asset directories.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico'
          # EXCLUDE IN PROGRESS FOR BUILD, COMMENT OUT WHEN WORKING LOCALLY
          # ,'rosetta'
          ]



# Force inclusion of directories and/or files in the conversion.
# .htaccess is a good example since dotfiles are excluded by default.
include: ['.htaccess']

# Default post path style
permalink: /:title/

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: true

# Split posts over multiple subdirectories called “page2”, “page3”, … “pageN”
paginate: 5
paginate_path: 'page:num'

# Markdown library
markdown: maruku

# Use Pygments to highlight code blocks
pygments: true

authors:
  nclud:
    name: "nclud"
    image: /img/nclud-logo.png
    twitter: nclud
    bio: "A creative design agency focused on unique, stylish and usable experiences across a multitude of verticals, mediums and devices. We work with early stage start-ups, to the Fortune 100, and everyone in between."
  kerry:
    name: "Kerry Gunther"
    image: /img/authors/kerry.jpg
    twitter: kerrygunther
    bio: "Kerry is the CEO of nclud. In addition to the web, Kerry enjoys all things LEGO."
  jesse:
    name: "Jesse Shawl"
    image: https://0.gravatar.com/avatar/495991dab64918eb18680073115163aa?d=https%3A%2F%2Fidenticons.github.com%2F0837445cdfc525ca7dcf22cc5b2f8747.png&r=x&s=440
    twitter: jshawl
    bio: "Jesse Shawl is a Front End Developer at nclud - whose focus intersects web performance and cutting edge browser interactivity. He's an open source advocate who enjoys building tools for the web with third party API's and mesmerizing CSS animations."
  max:
    name: "Maxim Leyzerovich"
    image: https://en.gravatar.com/userimage/2389570/877e069dddc3cf465159bd80dd180227.png?size=256
    twitter: duqe
    bio: "Maxim is the Senior Experience Designer at nclud, focused on the visual conception and interface development for interactive products &ndash; he is also the brand evangelist for the company our community, the industry, &amp; our clients."
  mannie:
    name: "William Mannie"
    image: /img/nclud-logo.png 
    twitter: tripleOGstatus
    bio: "Mannie is an intern at nclud - that loves all things digital"
  joe:
    name: "Joe Corbett"
    image: https://pbs.twimg.com/profile_images/2135049216/joe_bigger.png
    twitter: joecorbett
    bio: "Joe is the COO at nclud, and focuses on providing the team with the best systems and tools in the business to ensure we consistantly deliver the leading creative solutions in our industry."


prose:
  rooturl: "app/_posts"
  media: "app/uploads"
  metadata:
    app/_posts:
      - name: "title"
        field:
          element: "text"
          value: "Title"
      - name: "featured-image"
        field:
          element: "text"
          label: "Featured Image"
      - name: "layout"
        field:
          element: "hidden"
          value: post
      - name: "comments"
        field:
          element: "checkbox"
          label: "Enable Comments"
          value: true
      - name: "summary"
        field:
          element: "textarea"
          label: "Summary"
      - name: "author"
        field:
          element: "select"
          label: "Author"
          options:
            - name : 'nclud'
              value: 'nclud'
              twitter: nclud
            - name : 'Jesse Shawl'
              value: 'jesse'
            - name : 'Kerry Gunther'
              value: 'kerrygunther'
            - name : 'Joe Corbett'
              value: 'joe'
            - name : 'William Mannie'
              value: 'Mannie'
